### ISSUE TITLE
Add WordPress 4.5 customizer support

### ISSUE THREAD

**Issue by alanorth** [themejunkie/bulan#14]
Need to add support for WordPress 4.5's live refresh in the theme customizer, see: http://wptavern.com/get-your-widgets-ready-for-wordpress-4-5

**Comment by gasatrya** [comment]
Hi, we will add this support when 4.5 released.

**Comment by gricey432** [comment]
Any word on this now that 4.5 has been out for a while?

**Comment by gasatrya** [comment]
We're busy right now, we will update it soon. We're sorry about that.

**Comment by gasatrya** [comment]
https://github.com/themejunkie/bulan/commit/11af41f1e57cb66ee508c80464d61ad0183830d0
